Repository GDSC-snowflowerthon/Nightary-team12-mobile, pull requests merged in 2024-01, with the labels that each got.

#5 🗃feat: 데이터 모델 클래스 추가/앱 초기 실행 시 데이터베이스 테이블 생성
  lib/database_helper.dart
  lib/domains/sleep_record.dart
  lib/domains/user.dart
  lib/domains/white_noise.dart
  lib/main.dart
  pubspec.yaml
Labels: feature, 동겸

#10 ✨ Feat: white noise
  assets/images/white_noise_1.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/domains/sleep_record.dart
  lib/domains/user.dart
  lib/domains/white_noise.dart
  lib/utilities/music_visualizer.dart
  lib/viewModels/white_noise/white_noise_viewmodel.dart
  lib/views/white_noise/white_noise_screen.dart
  pubspec.yaml
Labels: feature, fix, 상현

#14 ✨ Feat: Statistic Screen
  lib/bindings/root_binding.dart
  lib/bindings/statistic_binding.dart
  lib/viewModels/statistic/fragment/abstract_recent_viewmodel.dart
  lib/viewModels/statistic/fragment/seven_recent_viewmodel.dart
  lib/viewModels/statistic/fragment/thirty_recent_viewmodel.dart
  lib/viewModels/statistic/statistic_screen.dart
  lib/views/base/base_screen.dart
  lib/views/statistic/recent_fragment.dart
  lib/views/statistic/statistic_screen.dart
  lib/views/statistic/widgets/average_sleep_time.dart
  lib/views/statistic/widgets/liability_chart.dart
  lib/views/statistic/widgets/sleep_time_chart.dart
  lib/views/statistic/widgets/statistic_tile.dart
  lib/widgets/custom_time_chart/chart.dart
  lib/widgets/custom_time_chart/components/chart_type.dart
  lib/widgets/custom_time_chart/components/painter/amount_chart/amount_bar_painter.dart
  lib/widgets/custom_time_chart/components/painter/amount_chart/amount_x_label_painter.dart
  lib/widgets/custom_time_chart/components/painter/amount_chart/amount_y_label_painter.dart
  lib/widgets/custom_time_chart/components/painter/bar_painter.dart
  lib/widgets/custom_time_chart/components/painter/border_line_painter.dart
  lib/widgets/custom_time_chart/components/painter/chart_engine.dart
  lib/widgets/custom_time_chart/components/painter/time_chart/time_bar_painter.dart
  lib/widgets/custom_time_chart/components/painter/time_chart/time_x_label_painter.dart
  lib/widgets/custom_time_chart/components/painter/time_chart/time_y_label_painter.dart
  lib/widgets/custom_time_chart/components/painter/x_label_painter.dart
  lib/widgets/custom_time_chart/components/painter/y_label_painter.dart
  lib/widgets/custom_time_chart/components/scroll/custom_scroll_physics.dart
  lib/widgets/custom_time_chart/components/scroll/my_single_child_scroll_view.dart
  lib/widgets/custom_time_chart/components/tooltip/tooltip_overlay.dart
  lib/widgets/custom_time_chart/components/tooltip/tooltip_shape_border.dart
  lib/widgets/custom_time_chart/components/tooltip/tooltip_size.dart
  lib/widgets/custom_time_chart/components/translations/translations.dart
  lib/widgets/custom_time_chart/components/utils/context_utils.dart
  lib/widgets/custom_time_chart/components/utils/time_assistant.dart
  lib/widgets/custom_time_chart/components/utils/time_data_processor.dart
  lib/widgets/custom_time_chart/components/view_mode.dart
  lib/widgets/custom_time_chart/time_chart.dart
  pubspec.yaml
Labels: feature, 형준

#15 ✨ feat: healthkit 패키지 추가
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/bindings/onboarding_binding.dart
  lib/utilities/app_pages.dart
  lib/utilities/app_routes.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/viewModels/setting/setting_screen.dart
  lib/views/home/home_screen.dart
  lib/views/onboarding/onboarding_screen.dart
  lib/views/root/root_screen.dart
  lib/views/setting/setting_screen.dart
  lib/widgets/custom_time_chart/components/scroll/custom_scroll_physics.dart
  lib/widgets/custom_time_chart/components/scroll/my_single_child_scroll_view.dart
  lib/widgets/custom_time_chart/components/tooltip/tooltip_overlay.dart
  pubspec.yaml
Labels: feature, 상현

#18 ✨ feat: ORM, SharedPreferences 적용
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/apps/database.dart
  lib/apps/database.g.dart
  lib/apps/factory/database_factory.dart
  lib/apps/factory/shared_preference_factory.dart
  lib/bindings/init_binding.dart
  lib/bindings/statistic_binding.dart
  lib/database_helper.dart
  lib/domains/dao/sleep_record_dao.dart
  lib/domains/dao/sleep_record_dao.g.dart
  lib/domains/dao/white_noise_dao.dart
  lib/domains/dao/white_noise_dao.g.dart
  lib/domains/entities/sleep_record.dart
  lib/domains/entities/white_noise.dart
  lib/domains/sleep_record.dart
  lib/domains/types/e_source.dart
  lib/domains/user.dart
  lib/domains/white_noise.dart
  lib/main.dart
  lib/main_app.dart
  lib/providers/sleep_record_local_provider.dart
  lib/providers/temp
  lib/providers/user_local_provider.dart
  lib/providers/white_noise_local_provider.dart
  lib/repositories/sleep_record_repository.dart
  lib/repositories/temp.dart
  lib/repositories/user_repository.dart
  lib/repositories/white_noise_repository.dart
  pubspec.yaml
Labels: feature, 형준

#16 ✨ Feat: Create SettingScreen
  assets/images/profile.png
  ios/Podfile.lock
  lib/bindings/root_binding.dart
  lib/viewModels/setting/setting_screen.dart
  lib/viewModels/setting/setting_viewmodel.dart
  lib/views/setting/setting_screen.dart
Labels: feature, 현정

#23 ✨ 🚑 feat,fix: OnBodingScreen 상태 연결 및 Flutter IOS 최소버전 13 변경
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/apps/factory/shared_preference_factory.dart
  lib/middlewares/name_middlewares.dart
  lib/providers/user_local_provider.dart
  lib/repositories/user_repository.dart
  lib/utilities/app_pages.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/onboarding/onboarding_screen.dart
Labels: feature, fix, 형준

#27 ✨ feat: Statistics Screen Data 연동, 충돌 해결, UI 오류 수정
  lib/apps/factory/database_factory.dart
  lib/domains/dao/sleep_record_dao.dart
  lib/main.dart
  lib/providers/sleep_record_local_provider.dart
  lib/repositories/sleep_record_repository.dart
  lib/utilities/log_system.dart
  lib/viewModels/statistic/fragment/abstract_recent_viewmodel.dart
  lib/viewModels/statistic/fragment/seven_recent_viewmodel.dart
  lib/viewModels/statistic/fragment/thirty_recent_viewmodel.dart
  lib/views/analyze/analyze_screen.dart
  lib/views/statistic/recent_fragment.dart
  lib/views/statistic/statistic_screen.dart
  lib/views/statistic/widgets/average_sleep_time.dart
  lib/views/statistic/widgets/liability_chart.dart
  lib/views/statistic/widgets/sleep_time_chart.dart
  lib/views/statistic/widgets/statistic_tile.dart
  lib/widgets/custom_time_chart/chart.dart
  lib/widgets/custom_time_chart/components/view_mode.dart
  pubspec.yaml
Labels: feature, fix, 형준

#31 ✨ 🚑 feat, fix: #28 급한 데이터 연결 완료
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/apps/database.dart
  lib/apps/database.g.dart
  lib/apps/factory/database_factory.dart
  lib/bindings/init_binding.dart
  lib/bindings/statistic_binding.dart
  lib/domains/dao/sleep_record_dao.dart
  lib/domains/dao/time_slice_dao.dart
  lib/domains/dao/time_slice_dao.g.dart
  lib/domains/entities/time_slice.dart
  lib/main.dart
  lib/providers/sleep_record_local_provider.dart
  lib/providers/time_slice_local_provider.dart
  lib/providers/user_local_provider.dart
  lib/repositories/sleep_record_repository.dart
  lib/repositories/user_repository.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/onboarding/onboarding_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/onboarding/onboarding_screen.dart
  lib/views/statistic/statistic_screen.dart
  lib/views/statistic/widgets/liability_chart.dart
  lib/views/statistic/widgets/sleep_time_chart.dart
  lib/views/statistic/widgets/statistic_tile.dart
Labels: feature, fix, 형준

#33 🚑 fix: 기본 알람 시간 추가 및 홈 화면 UI 로직 수정
  lib/providers/user_local_provider.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/views/home/home_screen.dart
Labels: fix, 형준

#34 feat: 수면 그래프->차트로 변경, API 분리, 서버통신
  ios/Podfile.lock
  lib/providers/sleep_record_local_provider.dart
  lib/repositories/sleep_record_repository.dart
  lib/viewModels/analyze/analyze_viewmodel.dart
  lib/viewModels/setting/setting_viewmodel.dart
  lib/views/analyze/analyze_screen.dart
  lib/views/analyze/widgets/predict_sleep_time_chart.dart
Labels: feature, 동겸

#36 chore: build 1.0.0+5
  ios/Podfile.lock
  lib/main.dart
  lib/providers/sleep_record_local_provider.dart
  lib/repositories/sleep_record_repository.dart
  pubspec.yaml
Labels: feature, 상현
